import Head from "next/head";
import CarouselProduct, { ModalContainer } from "../components/CarouselProduct";
import Navbar from "../components/Navbar";
import ProductCount from "../components/ProductCount";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <CarouselProduct className={styles.product} />
        <article className={styles.article}>
          <h3 className={styles.h3}>Sneaker Company</h3>
          <h1 className={styles.h1}>Fall Limited Edition Sneakers</h1>
          <p className={styles.disc}>
            These low-profile sneakers are your perfect casual wear companion.
            Featuring a durable rubber outer sole, they’ll withstand everything
            the weather can offer.
          </p>
          <div className={styles.priceBox}>
            <span className={styles.price}>$125.00</span>
            <span>50%</span>
            <del>$250.00</del>
          </div>
          <ProductCount />
        </article>
      </main>
    </>
  );
}
